// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypfapcqyrprzihklxcwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwZmFwY3F5cnByemloa2x4Y3dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1OTAzMDcsImV4cCI6MjA2MDE2NjMwN30.q1yAHira68V5DM8uceIzg1r7rJ8vgldGy17Vns0TsnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);